import React from "react";

        interface Iprops {
        style: any;
        onClick: () => void;
        color: string;
        iconSize: number;
      };
export class AddIcon extends React.PureComponent<Iprops, any> {}
export class AirPlaneIcon extends React.PureComponent<Iprops, any> {}
export class AnalyseIcon extends React.PureComponent<Iprops, any> {}
export class AnalyseResultIcon extends React.PureComponent<Iprops, any> {}
export class AntiFullViewIcon extends React.PureComponent<Iprops, any> {}
export class ArrowAsceIcon extends React.PureComponent<Iprops, any> {}
export class ArrowBotomIcon extends React.PureComponent<Iprops, any> {}
export class ArrowBottomIcon extends React.PureComponent<Iprops, any> {}
export class ArrowDescIcon extends React.PureComponent<Iprops, any> {}
export class ArrowLeftIcon extends React.PureComponent<Iprops, any> {}
export class ArrowLeft2Icon extends React.PureComponent<Iprops, any> {}
export class ArrowLeftSetIcon extends React.PureComponent<Iprops, any> {}
export class ArrowRightIcon extends React.PureComponent<Iprops, any> {}
export class ArrowRightSetIcon extends React.PureComponent<Iprops, any> {}
export class ArrowSortIcon extends React.PureComponent<Iprops, any> {}
export class ArrowTopIcon extends React.PureComponent<Iprops, any> {}
export class AsceIcon extends React.PureComponent<Iprops, any> {}
export class AudioFrequencyIcon extends React.PureComponent<Iprops, any> {}
export class AuthOkIcon extends React.PureComponent<Iprops, any> {}
export class AuthRejectIcon extends React.PureComponent<Iprops, any> {}
export class AuthorityIcon extends React.PureComponent<Iprops, any> {}
export class AutoFixIcon extends React.PureComponent<Iprops, any> {}
export class BackIcon extends React.PureComponent<Iprops, any> {}
export class BackRunIcon extends React.PureComponent<Iprops, any> {}
export class BarIcon extends React.PureComponent<Iprops, any> {}
export class BaseStationIcon extends React.PureComponent<Iprops, any> {}
export class BaseStation2Icon extends React.PureComponent<Iprops, any> {}
export class BorderPauseIcon extends React.PureComponent<Iprops, any> {}
export class BorderPlayIcon extends React.PureComponent<Iprops, any> {}
export class BurshIcon extends React.PureComponent<Iprops, any> {}
export class CalculateIcon extends React.PureComponent<Iprops, any> {}
export class CalculatorIcon extends React.PureComponent<Iprops, any> {}
export class CalendarIcon extends React.PureComponent<Iprops, any> {}
export class CameraIcon extends React.PureComponent<Iprops, any> {}
export class CarRectIcon extends React.PureComponent<Iprops, any> {}
export class ChartBarIcon extends React.PureComponent<Iprops, any> {}
export class ChartCursorIcon extends React.PureComponent<Iprops, any> {}
export class ChinaMapIcon extends React.PureComponent<Iprops, any> {}
export class ClearIcon extends React.PureComponent<Iprops, any> {}
export class ClockIcon extends React.PureComponent<Iprops, any> {}
export class CloseIcon extends React.PureComponent<Iprops, any> {}
export class CompassIcon extends React.PureComponent<Iprops, any> {}
export class CopyIcon extends React.PureComponent<Iprops, any> {}
export class CycleIcon extends React.PureComponent<Iprops, any> {}
export class DaytimeIcon extends React.PureComponent<Iprops, any> {}
export class DeleteIcon extends React.PureComponent<Iprops, any> {}
export class DescIcon extends React.PureComponent<Iprops, any> {}
export class DisableIcon extends React.PureComponent<Iprops, any> {}
export class DivisionIcon extends React.PureComponent<Iprops, any> {}
export class DocFailureColoredIcon extends React.PureComponent<Iprops, any> {}
export class DocumentIcon extends React.PureComponent<Iprops, any> {}
export class Document2Icon extends React.PureComponent<Iprops, any> {}
export class DownloadIcon extends React.PureComponent<Iprops, any> {}
export class DownloadSheetIcon extends React.PureComponent<Iprops, any> {}
export class DrawIcon extends React.PureComponent<Iprops, any> {}
export class ElipisicsMoreIcon extends React.PureComponent<Iprops, any> {}
export class EquipmentWorkIcon extends React.PureComponent<Iprops, any> {}
export class ExitIcon extends React.PureComponent<Iprops, any> {}
export class Exit2Icon extends React.PureComponent<Iprops, any> {}
export class ExportIcon extends React.PureComponent<Iprops, any> {}
export class EyeCloseIcon extends React.PureComponent<Iprops, any> {}
export class EyeOpenIcon extends React.PureComponent<Iprops, any> {}
export class FileFolderIcon extends React.PureComponent<Iprops, any> {}
export class FilterIcon extends React.PureComponent<Iprops, any> {}
export class FinishIcon extends React.PureComponent<Iprops, any> {}
export class FireIcon extends React.PureComponent<Iprops, any> {}
export class FocusIcon extends React.PureComponent<Iprops, any> {}
export class FocusSignalIcon extends React.PureComponent<Iprops, any> {}
export class FreqPlanIcon extends React.PureComponent<Iprops, any> {}
export class FrequencySwitchIcon extends React.PureComponent<Iprops, any> {}
export class FullScreenIcon extends React.PureComponent<Iprops, any> {}
export class FullViewIcon extends React.PureComponent<Iprops, any> {}
export class GreenFinishColoredIcon extends React.PureComponent<Iprops, any> {}
export class GreenGoodIcon extends React.PureComponent<Iprops, any> {}
export class GridTileLayoutIcon extends React.PureComponent<Iprops, any> {}
export class HammerIcon extends React.PureComponent<Iprops, any> {}
export class Hammer2Icon extends React.PureComponent<Iprops, any> {}
export class HelpIcon extends React.PureComponent<Iprops, any> {}
export class HomeIcon extends React.PureComponent<Iprops, any> {}
export class IQRecordIcon extends React.PureComponent<Iprops, any> {}
export class IgnoreListIcon extends React.PureComponent<Iprops, any> {}
export class ImAnalysisIcon extends React.PureComponent<Iprops, any> {}
export class ImportIcon extends React.PureComponent<Iprops, any> {}
export class ItuIcon extends React.PureComponent<Iprops, any> {}
export class ListIcon extends React.PureComponent<Iprops, any> {}
export class LoadingMiniIcon extends React.PureComponent<Iprops, any> {}
export class LocationIcon extends React.PureComponent<Iprops, any> {}
export class Location2Icon extends React.PureComponent<Iprops, any> {}
export class LockIcon extends React.PureComponent<Iprops, any> {}
export class ManageIcon extends React.PureComponent<Iprops, any> {}
export class MapIcon extends React.PureComponent<Iprops, any> {}
export class MasterSlaveLayoutIcon extends React.PureComponent<Iprops, any> {}
export class MinusIcon extends React.PureComponent<Iprops, any> {}
export class MonitorCarIcon extends React.PureComponent<Iprops, any> {}
export class MoveIcon extends React.PureComponent<Iprops, any> {}
export class MoveLeftIcon extends React.PureComponent<Iprops, any> {}
export class MoveRightIcon extends React.PureComponent<Iprops, any> {}
export class MoveUpIcon extends React.PureComponent<Iprops, any> {}
export class MuteIcon extends React.PureComponent<Iprops, any> {}
export class NewArrowLeftSetIcon extends React.PureComponent<Iprops, any> {}
export class NewArrowRightSetIcon extends React.PureComponent<Iprops, any> {}
export class NewReplayListIcon extends React.PureComponent<Iprops, any> {}
export class NightIcon extends React.PureComponent<Iprops, any> {}
export class NotepadIcon extends React.PureComponent<Iprops, any> {}
export class OperatingStaffIcon extends React.PureComponent<Iprops, any> {}
export class ParamSettingsIcon extends React.PureComponent<Iprops, any> {}
export class PauseIcon extends React.PureComponent<Iprops, any> {}
export class PenIcon extends React.PureComponent<Iprops, any> {}
export class PenEditIcon extends React.PureComponent<Iprops, any> {}
export class PlanImgIcon extends React.PureComponent<Iprops, any> {}
export class PlayIcon extends React.PureComponent<Iprops, any> {}
export class PlaybackIcon extends React.PureComponent<Iprops, any> {}
export class ProtractorIcon extends React.PureComponent<Iprops, any> {}
export class RecIcon extends React.PureComponent<Iprops, any> {}
export class RecallIcon extends React.PureComponent<Iprops, any> {}
export class RedWarnColoredIcon extends React.PureComponent<Iprops, any> {}
export class ReduceIcon extends React.PureComponent<Iprops, any> {}
export class RefreshIcon extends React.PureComponent<Iprops, any> {}
export class RemoveIcon extends React.PureComponent<Iprops, any> {}
export class ReplayListIcon extends React.PureComponent<Iprops, any> {}
export class ReportIcon extends React.PureComponent<Iprops, any> {}
export class ReportLogIcon extends React.PureComponent<Iprops, any> {}
export class RevokeIcon extends React.PureComponent<Iprops, any> {}
export class RightArrowIcon extends React.PureComponent<Iprops, any> {}
export class RoundAddIcon extends React.PureComponent<Iprops, any> {}
export class RoundInfoIcon extends React.PureComponent<Iprops, any> {}
export class RoundMinusIcon extends React.PureComponent<Iprops, any> {}
export class RoundWarnIcon extends React.PureComponent<Iprops, any> {}
export class RoutePathIcon extends React.PureComponent<Iprops, any> {}
export class RulerIcon extends React.PureComponent<Iprops, any> {}
export class SatelliteIcon extends React.PureComponent<Iprops, any> {}
export class SearchIcon extends React.PureComponent<Iprops, any> {}
export class SettingIcon extends React.PureComponent<Iprops, any> {}
export class SignIcon extends React.PureComponent<Iprops, any> {}
export class SignOutIcon extends React.PureComponent<Iprops, any> {}
export class SignalIcon extends React.PureComponent<Iprops, any> {}
export class SortIcon extends React.PureComponent<Iprops, any> {}
export class SoundIcon extends React.PureComponent<Iprops, any> {}
export class SpecChartColoredIcon extends React.PureComponent<Iprops, any> {}
export class SpectrogramIcon extends React.PureComponent<Iprops, any> {}
export class StationMoreIcon extends React.PureComponent<Iprops, any> {}
export class StickIcon extends React.PureComponent<Iprops, any> {}
export class StopIcon extends React.PureComponent<Iprops, any> {}
export class Stop2Icon extends React.PureComponent<Iprops, any> {}
export class StoreIcon extends React.PureComponent<Iprops, any> {}
export class StrangeIcon1Icon extends React.PureComponent<Iprops, any> {}
export class SwitchStatisticsIcon extends React.PureComponent<Iprops, any> {}
export class TargetIcon extends React.PureComponent<Iprops, any> {}
export class TaskIcon extends React.PureComponent<Iprops, any> {}
export class TaskRunIcon extends React.PureComponent<Iprops, any> {}
export class TextIcon extends React.PureComponent<Iprops, any> {}
export class TileIcon extends React.PureComponent<Iprops, any> {}
export class TimeIcon extends React.PureComponent<Iprops, any> {}
export class TimeAxisIcon extends React.PureComponent<Iprops, any> {}
export class ToNextIcon extends React.PureComponent<Iprops, any> {}
export class ToSearchIcon extends React.PureComponent<Iprops, any> {}
export class ToolBoxIcon extends React.PureComponent<Iprops, any> {}
export class TranslateIcon extends React.PureComponent<Iprops, any> {}
export class TranslateColoredIcon extends React.PureComponent<Iprops, any> {}
export class TrapezeIcon extends React.PureComponent<Iprops, any> {}
export class TreeMapIcon extends React.PureComponent<Iprops, any> {}
export class TrumeptIcon extends React.PureComponent<Iprops, any> {}
export class UavIcon extends React.PureComponent<Iprops, any> {}
export class UnitConversionIcon extends React.PureComponent<Iprops, any> {}
export class UploadIcon extends React.PureComponent<Iprops, any> {}
export class UserIcon extends React.PureComponent<Iprops, any> {}
export class VerticalCloseIcon extends React.PureComponent<Iprops, any> {}
export class VerticalExpandIcon extends React.PureComponent<Iprops, any> {}
export class VerticalTileLayoutIcon extends React.PureComponent<Iprops, any> {}
export class VoiceIcon extends React.PureComponent<Iprops, any> {}
export class VoicedIcon extends React.PureComponent<Iprops, any> {}
export class WaittingIcon extends React.PureComponent<Iprops, any> {}
export class WatchDataIcon extends React.PureComponent<Iprops, any> {}
export class YellowWarnColoredIcon extends React.PureComponent<Iprops, any> {}
export class ZoomInIcon extends React.PureComponent<Iprops, any> {}
export class ZoomOutIcon extends React.PureComponent<Iprops, any> {}
