// <auto-generated />
using System;
using Magneto.Contract.UavDef;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace Magneto.Contract.Migrations
{
    [DbContext(typeof(UavDefDbContext))]
    partial class UavDefDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "7.0.13")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("Magneto.Contract.UavDef.Disposal", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("Content")
                        .HasColumnType("text");

                    b.Property<DateTime>("DateTime")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int>("RecordId")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("RecordId");

                    b.ToTable("uav_def_disposals");
                });

            modelBuilder.Entity("Magneto.Contract.UavDef.EvdAndFile", b =>
                {
                    b.Property<int>("EvdId")
                        .HasColumnType("integer")
                        .HasColumnOrder(0);

                    b.Property<int>("FileId")
                        .HasColumnType("integer")
                        .HasColumnOrder(1);

                    b.Property<int?>("EvidenceId")
                        .HasColumnType("integer");

                    b.Property<int?>("PlaybackFileId")
                        .HasColumnType("integer");

                    b.HasKey("EvdId", "FileId");

                    b.HasIndex("EvidenceId");

                    b.HasIndex("PlaybackFileId");

                    b.ToTable("uav_def_evd_and_files");
                });

            modelBuilder.Entity("Magneto.Contract.UavDef.Evidence", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("ElectronicFingerprint")
                        .HasColumnType("text");

                    b.Property<double>("LastFlightAltitude")
                        .HasColumnType("double precision");

                    b.Property<double>("LastFlightBearing")
                        .HasColumnType("double precision");

                    b.Property<double>("LastFlightHorizontalSpeed")
                        .HasColumnType("double precision");

                    b.Property<double>("LastFlightLatitude")
                        .HasColumnType("double precision");

                    b.Property<double>("LastFlightLongitude")
                        .HasColumnType("double precision");

                    b.Property<double>("LastFlightVerticalSpeed")
                        .HasColumnType("double precision");

                    b.Property<string>("Model")
                        .HasColumnType("text");

                    b.Property<double>("PilotLatitude")
                        .HasColumnType("double precision");

                    b.Property<double>("PilotLongitude")
                        .HasColumnType("double precision");

                    b.Property<double>("RadioFrequency")
                        .HasColumnType("double precision");

                    b.Property<int>("RecordId")
                        .HasColumnType("integer");

                    b.Property<double>("ReturnLatitude")
                        .HasColumnType("double precision");

                    b.Property<double>("ReturnLongitude")
                        .HasColumnType("double precision");

                    b.Property<string>("Type")
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.HasIndex("RecordId");

                    b.ToTable("uav_def_evidence");
                });

            modelBuilder.Entity("Magneto.Contract.UavDef.PlaybackFile", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<TimeSpan>("Duration")
                        .HasColumnType("interval");

                    b.Property<string>("FileName")
                        .HasColumnType("text");

                    b.Property<string>("FilePath")
                        .HasColumnType("text");

                    b.Property<int>("FileType")
                        .HasColumnType("integer");

                    b.Property<string>("Segments")
                        .HasColumnType("text");

                    b.Property<int>("TotalFrames")
                        .HasColumnType("integer");

                    b.Property<DateTime>("UpDatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.HasKey("Id");

                    b.ToTable("uav_def_playback_files");
                });

            modelBuilder.Entity("Magneto.Contract.UavDef.Record", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string[]>("DetectionEquipments")
                        .HasColumnType("text[]");

                    b.Property<TimeSpan>("Duration")
                        .HasColumnType("interval");

                    b.Property<int>("InvasionArea")
                        .HasColumnType("integer");

                    b.Property<int>("NumOfFlyingObjects")
                        .HasColumnType("integer");

                    b.Property<DateTime>("Time")
                        .HasColumnType("timestamp with time zone");

                    b.HasKey("Id");

                    b.ToTable("uav_def_records");
                });

            modelBuilder.Entity("Magneto.Contract.UavDef.UavPath", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<double>("Latitude")
                        .HasColumnType("double precision");

                    b.Property<double>("Longitude")
                        .HasColumnType("double precision");

                    b.Property<int>("RecordId")
                        .HasColumnType("integer");

                    b.Property<string>("UavSerialNum")
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.HasIndex("RecordId");

                    b.ToTable("uav_def_uav_paths");
                });

            modelBuilder.Entity("Magneto.Contract.UavDef.WhiteList", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("DroneSerialNum")
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.ToTable("uav_def_white_lists");
                });

            modelBuilder.Entity("Magneto.Contract.UavDef.Disposal", b =>
                {
                    b.HasOne("Magneto.Contract.UavDef.Record", "Record")
                        .WithMany("Disposals")
                        .HasForeignKey("RecordId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Record");
                });

            modelBuilder.Entity("Magneto.Contract.UavDef.EvdAndFile", b =>
                {
                    b.HasOne("Magneto.Contract.UavDef.Evidence", "Evidence")
                        .WithMany("EvdAndFiles")
                        .HasForeignKey("EvidenceId");

                    b.HasOne("Magneto.Contract.UavDef.PlaybackFile", "PlaybackFile")
                        .WithMany("EvdAndFiles")
                        .HasForeignKey("PlaybackFileId");

                    b.Navigation("Evidence");

                    b.Navigation("PlaybackFile");
                });

            modelBuilder.Entity("Magneto.Contract.UavDef.Evidence", b =>
                {
                    b.HasOne("Magneto.Contract.UavDef.Record", "Record")
                        .WithMany("Evidence")
                        .HasForeignKey("RecordId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Record");
                });

            modelBuilder.Entity("Magneto.Contract.UavDef.UavPath", b =>
                {
                    b.HasOne("Magneto.Contract.UavDef.Record", "Record")
                        .WithMany("UavPaths")
                        .HasForeignKey("RecordId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Record");
                });

            modelBuilder.Entity("Magneto.Contract.UavDef.Evidence", b =>
                {
                    b.Navigation("EvdAndFiles");
                });

            modelBuilder.Entity("Magneto.Contract.UavDef.PlaybackFile", b =>
                {
                    b.Navigation("EvdAndFiles");
                });

            modelBuilder.Entity("Magneto.Contract.UavDef.Record", b =>
                {
                    b.Navigation("Disposals");

                    b.Navigation("Evidence");

                    b.Navigation("UavPaths");
                });
#pragma warning restore 612, 618
        }
    }
}
